[project]
name = "cli-AI-assist"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.72.0",
]

[dependency-groups]
dev = []

[project.scripts]
ai = "cli_AI_assist:main"